name: (Action) npm install dependencies
description: "(Action) npm install dependencies"

inputs:
  NODE_AUTH_TOKEN:
    required: true
    description: 'GitHub Auth Token for npm to install packages, stored as secret'


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com/

    - name: Find node_modules cache
      id: cache-node_modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
              
    - name: Install dependencies
      if: steps.cache-node_modules.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}
