name: (Job) Conventional PR title

on:
  workflow_call:

jobs:
  conventional-pr-title:
    name: Conventional PR title
    runs-on: ubuntu-latest
    steps:

      - name: Check PR title format
        uses: aslafy-z/conventional-pr-title-action@v2.2.0
        with:
          success-state: Title follows the conventional commit specification.
          failure-state: Title does not follow the conventional commit specification.
          context-name: conventional-pr-title
          preset: conventional-changelog-conventionalcommits@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
