name: (Job) npm build & optionally upload artifact

on:
  workflow_call:
    inputs:
      upload:
        required: false
        default: false
        type: boolean
      gitlfs:
        required: false
        default: false
        type: boolean

jobs:
  build:
    name: Build & optionally upload artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: nschloe/action-cached-lfs-checkout@v1
        if: ${{ inputs.gitlfs }}

      - uses: actions/checkout@v3
        if: ${{ !inputs.gitlfs }}

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Find node_modules cache
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Get latest tag
        id: get-latest-tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

      - name: Build
        run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v3
        if: ${{ success() && inputs.upload }}
        with:
          name: build-${{ steps.get-latest-tag.outputs.tag }}
          path: dist
          retention-days: 1
          if-no-files-found: error
