name: (Job) npm publish

on:
  workflow_call:
    secrets:
      NODE_AUTH_TOKEN:
        required: true

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-${{ github.ref }}
          path: dist

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
