name: (Job) npm publish build

on:
  workflow_call:
    secrets:
      NODE_AUTH_TOKEN:
        required: true

jobs:
  build:
    name: npm publish build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          
      - name: Find node_modules cache
        id: cache-node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Get latest tag
        id: get-latest-tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)
      
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-${{ steps.get-latest-tag.outputs.tag }}
          path: dist

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
