name: Pull requests

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  conventional-pr-title:
    uses: ./.github/workflows/conventional-pr-title.yml

  install:
    uses: ./.github/workflows/npm-ci.yml
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}

  lint:
    needs: [install]
    uses: ./.github/workflows/npm-lint.yml
